env = Environment()

env['APP_TARGET'] = 'Prothesis'
env['APP_SOURCES'] = ['ProthesisApp.cpp', 'Calibrate.cpp', 'NIUser.cpp',
					'PParams.cpp', 'Stroke.cpp', 'StrokeManager.cpp',
					'Utils.cpp']

env['ASSETS'] = ['strokes/*']
env['DEBUG'] = 1

env = SConscript('../../../blocks/Cinder-NI/scons/SConscript',
	exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
